name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  dockerbuild:
    uses: eclipse-xfsc/dev-ops/.github/workflows/docker-maven.yml@main
    with:
      java_version: '18'
      deploy_mode: 'jar'
  helm:
    uses: eclipse-xfsc/dev-ops/.github/workflows/helm.yml@main
    with:
      buildContext:  "deployment/helm"